import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
type Project={title:string;type:string;description:string;stack:string[];number:string};
type Plan={name:string;price:string;intro:string;featured?:boolean;items:string[];pages:string;timeline:string;revisions:string;support:string;integrations:string};
const projects:Project[]=[
{number:"01",title:"MONTÊ",type:"E-commerce",description:"Experiência digital premium para uma marca de moda, com catálogo, checkout e uma interface pensada para conversão.",stack:["React","TypeScript","Render"],},
{number:"02",title:"KEY",type:"Brand / Commerce",description:"Direção digital para uma marca de moda com identidade visual minimalista e experiência de compra editorial.",stack:["UI/UX","Frontend","Deploy"],},
{number:"03",title:"Portfolio Lab",type:"Digital Product",description:"Sistemas de portfólio e apresentação comercial criados para transformar projetos em novas oportunidades.",stack:["React","Motion","SEO"],}
];
const plans:Plan[]=[
{name:"Essencial",price:"R$ 1.500",intro:"Uma presença digital enxuta e profissional.",pages:"Até 4 páginas/telas",timeline:"7–10 dias úteis",revisions:"2 rodadas de ajustes",support:"7 dias após publicação",integrations:"Formulário/WhatsApp, analytics e domínio",items:["Design visual responsivo","Desenvolvimento frontend","SEO básico","Publicação no Render","Otimização para celular","Configuração de domínio"]},
{name:"Profissional",price:"R$ 3.000",intro:"Uma experiência completa para apresentar e vender.",featured:true,pages:"Até 8 páginas/telas",timeline:"12–18 dias úteis",revisions:"3 rodadas de ajustes",support:"15 dias após publicação",integrations:"Formulários, WhatsApp, analytics e integrações externas",items:["Tudo do Essencial","Arquitetura de navegação personalizada","Animações e microinterações","Parallax e transições avançadas","SEO técnico e Open Graph","Integrações personalizadas","Deploy e configuração de produção"]},
{name:"Premium",price:"R$ 5.000",intro:"Uma experiência digital sob medida, do conceito ao lançamento.",pages:"Projeto sob medida",timeline:"20–30 dias úteis",revisions:"4 rodadas de ajustes",support:"30 dias após publicação",integrations:"Integrações sob escopo e APIs quando aplicável",items:["Tudo do Profissional","Direção visual exclusiva","Arquitetura completa de experiência","Motion design e interações avançadas","Estrutura preparada para evolução","Integrações sob medida","Acompanhamento pós-lançamento"]},
];
function Logo(){return <a className="logo" href="#top" aria-label="Vitor Volpato início"><img src="/logo.svg" alt="VV"/></a>}
function App(){
 const [active,setActive]=useState<Plan|null>(null);
 useEffect(()=>{const els=[...document.querySelectorAll<HTMLElement>("[data-reveal]")];const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("is-visible")}),{threshold:.12});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[]);
 useEffect(()=>{const onScroll=()=>document.documentElement.style.setProperty("--scroll",String(window.scrollY));window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);
 return <div id="top">
  <header className="nav"><Logo/><nav><a href="#projetos">Projetos</a><a href="#planos">Planos</a><a href="#processo">Processo</a><a href="#contato">Contato</a></nav><a className="nav-cta" href="#contato">Vamos conversar <span>↗</span></a></header>
  <main>
   <section className="hero section-dark"><div className="hero-grid"></div><div className="hero-orb orb-a"></div><div className="hero-orb orb-b"></div><div className="hero-content" data-reveal><p className="eyebrow">VITOR VOLPATO / DIGITAL BUILDER</p><h1>Eu transformo<br/><em>ideias</em> em experiências digitais.</h1><p className="hero-copy">Desenvolvimento web, interfaces e produtos digitais com direção visual, tecnologia e atenção aos detalhes.</p><div className="hero-actions"><a className="button button-light" href="#projetos">Ver projetos <span>↓</span></a><a className="text-link" href="#planos">Conhecer planos <span>↘</span></a></div></div><div className="hero-meta"><span>SCROLL TO EXPLORE</span><span>01 — 07</span></div><div className="parallax-mark" style={{transform:"translate3d(0,calc(var(--scroll,0px)*-.08),0)"}}>VV</div></section>
   <section id="projetos" className="section-light projects"><div className="section-head" data-reveal><div><p className="eyebrow dark">SELECTED WORK</p><h2>Projetos que<br/><em>ganham vida.</em></h2></div><p className="section-intro">Uma seleção de trabalhos, produtos e experiências digitais desenvolvidos com foco em presença, clareza e resultado.</p></div><div className="project-list">{projects.map((p,i)=><article className="project" data-reveal key={p.title}><div className={"project-visual visual-"+i}><span>{p.number}</span><div className="visual-word">{p.title}</div></div><div className="project-info"><p className="project-type">{p.type}</p><h3>{p.title}</h3><p>{p.description}</p><div className="chips">{p.stack.map(s=><span key={s}>{s}</span>)}</div><button className="arrow-btn" aria-label={"Ver projeto "+p.title}>↗</button></div></article>)}</div></section>
   <section id="planos" className="section-dark plans"><div className="section-head" data-reveal><div><p className="eyebrow">SERVICES / 03</p><h2>Escolha o nível<br/>da sua <em>ideia.</em></h2></div><p className="section-intro">Três formatos para tirar seu projeto do papel. Clique em qualquer plano para ver exatamente o que está incluído.</p></div><div className="plans-grid">{plans.map((p,i)=><button className={"plan-card "+(p.featured?"featured":"")} onClick={()=>setActive(p)} key={p.name} data-reveal><div className="plan-top"><span>0{i+1}</span>{p.featured&&<b>MAIS PROCURADO</b>}</div><h3>{p.name}</h3><p className="plan-intro">{p.intro}</p><div className="price">{p.price}<small> / projeto</small></div><div className="plan-tease">{p.items.slice(0,3).map(x=><span key={x}>+ {x}</span>)}</div><span className="plan-link">Ver tudo ↗</span></button>)}</div></section>
   <section id="processo" className="section-light process"><div className="section-head" data-reveal><div><p className="eyebrow dark">PROCESS / 04</p><h2>Do primeiro<br/>briefing ao <em>launch.</em></h2></div></div><div className="process-grid">{["Briefing & direção","Design & protótipo","Desenvolvimento","Lançamento"].map((x,i)=><div className="step" data-reveal key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Entendemos objetivo, público, conteúdo e o que precisa acontecer para o projeto funcionar.","Transformamos a estratégia em uma linguagem visual e uma experiência navegável.","Construímos a interface, animações, responsividade e integrações definidas no escopo.","Publicamos, testamos e entregamos a estrutura pronta para continuar evoluindo."][i]}</p></div>)}</div></section>
   <section className="section-dark about"><div className="about-inner" data-reveal><p className="eyebrow">ABOUT / 05</p><h2>Design encontra<br/><em>código.</em></h2><p className="about-copy">Meu trabalho conecta direção visual e desenvolvimento para criar sites que não parecem apenas bonitos — eles têm uma lógica, uma experiência e uma função.</p><div className="stack-row">{["React","TypeScript","JavaScript","CSS","GitHub","Render","Supabase","Figma"].map(x=><span key={x}>{x}</span>)}</div></div></section>
   <section id="contato" className="contact section-light"><div data-reveal><p className="eyebrow dark">CONTACT / 06</p><h2>Tem uma ideia?<br/><em>Vamos construir.</em></h2><p>Conte o que você está imaginando e eu retorno com os próximos passos.</p><a className="contact-mail" href="mailto:vitorvolpe14@gmail.com">vitorvolpe14@gmail.com <span>↗</span></a></div></section>
  </main>
  <footer className="footer section-dark"><Logo/><p>© {new Date().getFullYear()} Vitor Volpato</p><a href="#top">Voltar ao topo ↑</a></footer>
  {active&&<div className="modal-backdrop" onClick={()=>setActive(null)}><div className="plan-modal" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setActive(null)} aria-label="Fechar">×</button><p className="eyebrow dark">PLANO SELECIONADO</p><h2>{active.name}</h2><div className="modal-price">{active.price}</div><p className="modal-intro">{active.intro}</p><div className="modal-grid"><div><h4>Incluído</h4><ul>{active.items.map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>Escopo</h4><dl><div><dt>Páginas/telas</dt><dd>{active.pages}</dd></div><div><dt>Prazo estimado</dt><dd>{active.timeline}</dd></div><div><dt>Revisões</dt><dd>{active.revisions}</dd></div><div><dt>Suporte</dt><dd>{active.support}</dd></div><div><dt>Integrações</dt><dd>{active.integrations}</dd></div></dl></div></div><a className="button button-dark modal-cta" href={"mailto:vitorvolpe14@gmail.com?subject=Interesse no plano "+active.name}>Quero este plano ↗</a></div></div>}
 </div>
}
createRoot(document.getElementById("root")!).render(<App/>);